{{- if and (eq (.Values.defaultDenyNetworkPolicy.enabled | toString) "true") .Values.networkPolicy.postgresql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-postgresql-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgresql-db
  policyTypes:
  - Ingress
  - Egress
  {{- with .Values.networkPolicy.postgresql.ingress }}
  ingress:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.postgresql.egress }}
  egress:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
